### ISSUE TITLE
NuGet Publisher shouldn't abort on first conflict (409)

### ISSUE THREAD

**Issue by thorbenw** [Microsoft/vsts-tasks#2119]
There are situation where I'd like to make NuGet Publisher ignore conflicts, i.e. recognize the package is already up to date and continue publishing in case there are multiple packages found.
#1511 introduced a workaround, but this doesn't add that "publish if there's anything new" capability I'm looking for.

**Comment by zjrunner** [comment]
This is something we'll consider, but today we can't reliably get this information out of nuget to know the difference between an ok failure (409) and a fatal attempt.  We have potential future plans to change how we push packages to allow more control here, but not in the Dev15 timeline.

**Comment by abatishchev** [comment]
+1. An ability to suppress 409 Conflict only and fail on others is very needed!

**Comment by zjrunner** [comment]
I've captured the request internally in our feature board (683673) to consider for the future.

**Comment by abatishchev** [comment]
Hey Zack, can you please send me the link to alexbat@?

**Comment by zjrunner** [comment]
I'll just post it here - nothing to hide, just not accessible to most people:
Feature 683673: Improve NugetPublisher Task
https://mseng.visualstudio.com/VSOnline/_workitems/edit/683673 

(gave it a generic name so we could roll up several items in a feature and then expand them out when we take them on.  Helps ensure things don't get lost in a flooded backlog over time)

**Comment by Zazcallabah** [comment]
Instead of suppressing the 409, could the build task first check if the current version of the package has already been published - and only attempt publish if not?

also, if you close these issues, there is no way for users (i.e. me) to get a notification when they have been fixed?

**Comment by abatishchev** [comment]
hi @zjrunner, do you know what is current status? the link above doesn't work anymore, at least to me.

**Comment by alexmullans** [comment]
@abatishchev we're spec'ing these improvements now, hoping to start on them next sprint. Feature 564185: NuGet producer build tasks v2 https://mseng.visualstudio.com/VSOnline/_workitems/edit/564185?fullScreen=false

**Comment by alexmullans** [comment]
We're adding a new option to this task called "Allow duplicates to be skipped" that should address this issue. I'm reopening this issue for now to allow for notifications when we ship the fix.

**Comment by michelkamp** [comment]
Hi , 

it would be great to have this option "Allow duplicates to be skipped" implemented. I have 1 solution containing several packages. i want to build this with 1 build plan. Now the Devs have to update all package numbers if they only have to change one package. So not a good way do doing. 

This here any workaround for this now ? Should i use the nuget packager and apply only the project files / nuget. The issue in that case is that i build dot net core projects and this step looks like not working with dot net core.

Any help would be great.
thanks,
michel

**Comment by abatishchev** [comment]
The work on new version is in progress to my knowledge. For now a workaround would be either writing own PowerShell script to publish which won't fail on conflict, or create publish package step for each package independently and make them to continue on error. This will make your build orange but it's better than updating all versions each time.

**Comment by alexmullans** [comment]
@michelkamp we're taking the "Allow duplicates to be skipped" work this sprint. Should be available in about a month.

**Comment by alexmullans** [comment]
This is fixed by #4397.

**Comment by michelkamp** [comment]
Is it fix active already ???

Is still get an error :

==============================================================================
Task         : NuGet Publisher
Description  : Uploads nupkg files to a NuGet server
Version      : 0.2.34
Author       : Lawrence Gripper
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=627417)
==============================================================================
C:\Windows\system32\chcp.com 65001
Active code page: 65001
Detected NuGet version 3.5.0.1938 / 3.5.0
SYSTEMVSSCONNECTION exists true
d:\a\_tasks\NuGetPublisher_xxxxxxxxx\0.2.34\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe push -NonInteractive "d:\a\3\s\Portal\Main\xxxxxxx.Portal\Portal.AzureBilling.Client\bin\any cpu\release\xxxxxxxx.Client.1.0.70.nupkg" -Source https://xxxxxxx.pkgs.visualstudio.com/_packaging/xxxxxx-Packages-Private/nuget/v3/index.json -ApiKey VSTS
Pushing xxxxxxxx.Client.1.0.70.nupkg to 'https://xxxxxx.pkgs.visualstudio.com/_packaging/xxxxxxxxx/nuget/v2/'...
  PUT https://xxxxx.pkgs.visualstudio.com/_packaging/xxxxxxxx/nuget/v2/
  Conflict https://xxxxxx.pkgs.visualstudio.com/_packaging/xxxxxxxxx/nuget/v2/ 1001ms
Response status code does not indicate success: 409 (Conflict).
Error: d:\a\_tasks\NuGetPublisher_xxxxxxxx\0.2.34\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe failed with return code: 1
Packages failed to publish

Michel

**Comment by alexmullans** [comment]
It is not. We need to finish up the linked PR and get it deployed, which will happen in 3 weeks.

**Comment by elitas** [comment]
@alexmullans : Three weeks has passed, when is the deploy due?

**Comment by alexmullans** [comment]
Will be finished tomorrow (Thursday).

**Comment by Abdruggi** [comment]
Any schedule when it will be available for tfs on premise?

**Comment by michelkamp** [comment]
I can confirm that fixed already !

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexmullans** [comment]
Should land in TFS 2018.

**Comment by sandorfr** [comment]
The `Allow duplicates to be skipped` option is missing on External Nuget Server. I think this is needed there as well  ;)

**Comment by alexmullans** [comment]
Unfortunately, that feature relies on a custom NuGet client and APIs that are only available in Visual Studio Team Services, so we can't enable it for external NuGet servers.

**Comment by abatishchev** [comment]
It's impossible to catch HTTP exceptions and swallow those which have status 409 Conflict? I understand that internally it's more complex but in the end or the day that's what it is, isn't it?

**Comment by sandorfr** [comment]
If what @abatishchev is suggesting is not possible, maybe having the task skipping symbols automatically would be great.

**Comment by zjrunner** [comment]
@abatishchev , when using nuget.exe your response codes have historically been only 0 or 1.  It was success or failure.  In this case, ignoring a conflict would also ignore invalid uploads and other types of connectivity errors.  To go beyond that you need to get into verbose output and log scraping which generally aren't reliable, especially across user-configurable nuget versions.  Since we own the VSTS Server implementation for nuget, we can create a more direct-line to do what you're talking about and add some other efficiencies, but for other host servers we go through nuget.exe as the standard.

**Comment by abatishchev** [comment]
I see. Should we then we/you go to the NuGet team and ask to expose HTTP statuses properly?

**Comment by zjrunner** [comment]
Yes, but it has been an open request in nuget since 2015 (https://github.com/NuGet/Home/issues/1630).  The last workable suggestion in that thread was to list, then publish.  That still is exposed to race failures.

**Comment by alexmullans** [comment]
@sandorfr great feedback, we used to exclude those, and I think we could add that back to the default. For existing builds, you can add ;!$(Build.ArtifactStagingDirectory)/*.symbols.nupkg to your publish path to exclude symbols packages.

**Comment by doorman02** [comment]
Hi @alexmullans what´s the status, is there a way to skip duplicates using the nuget command line tool? I have TFS2018 installed. Thanks

**Comment by alexmullans** [comment]
@doorman02 there is not, unfortunately. The VSTS build task uses a VSTS-specific tool to push packages that can understand and react to the 409.

**Comment by michelkamp** [comment]
if you use the new NuGet push build step you have a option "Allow duplicates to be skipped" described as : If you continually publish a set of packages and only change the version number of the subset of packages that changed, use this option. It allows the task to report success even if some of your packages are rejected with 409 Conflict errors.

This option is currently only available on Visual Studio Team Services and using Windows agents. If NuGet.exe encounters a conflict, the task will fail.

**Comment by snelljef** [comment]
@michelkamp Is there a timeline or workaround for TFS On-premise users?

**Comment by mlooise** [comment]
@michelkamp Could this feature also be made available for the on-prem users? Maybe with a marketplace plugin? I'm also searching for a workaround. At the moment i'm using continue on error but always get release failures using this approach

**Comment by alexmullans** [comment]
This feature is also available on-premises as of TFS 2018.

**Comment by snelljef** [comment]
@alexmullans It is? Unless it's misconfigured on my end I have to disagree. I am running TFS 2018.3 and it explicitly warns that it does not work with on-premise installs with the following text:

This option is currently only available on Visual Studio Team Services and using Windows agents. If NuGet.exe encounters a conflict, the task will fail.

I am using the NuGet task version 2.*

**Comment by alexmullans** [comment]
@snelljef Right you are, my apologies. I thought we'd shipped that on-premises at some point. I've put an item on our backlog to consider when we do planning for Q1.

**Comment by chouhanaditya** [comment]
Hi @alexmullans,

I am getting same error - 'error: Response status code does not indicate success: 409 (Conflict - The feed already contains package'. I am using azure pipeline YAML task _**DotNetCoreCLI@2- Pack and Publish**_ for publishing nuget packages. The flag 'Allow duplicates to be skipped' or property ' allowPackageConflicts: true' doesn't seem to be working for me since I am using Ubuntu build agent. Can you please asssist me

**Comment by zjrunner** [comment]
This won't work outside of windows agents, it is making use of a custom uploader instead of nuget.exe that happened to be written in .net framework at the time.  Your best bet at this point is to follow the earlier suggestions of doing a list, then the publish as needed.  It looks like the issue mentioned earlier in this thread is still open (https://github.com/NuGet/Home/issues/1630), but it references some other efforts in just the last week attempting to make a fix in nuget to support this fully.

**Comment by RehanSaeed** [comment]
Any plans to make `allowPackageConflicts: true` work on Ubuntu or Mac?

**Comment by zjrunner** [comment]
no, the custom tool beneath it won't become xplat.  we're moving in a direction of encouraging the use of our auth-only task and then using raw nuget/msbuild/dotnet in batch tasks or YAML build for a cleaner flow where we're less in the way.  nuget had a couple issues open at one time about directly supporting return codes so you could differentiate on the client between a failed upload and a conflict upload, I'd recommend finding and taking part in those threads to help drive a more native solution
