### ISSUE TITLE
Xcode package task assumes that the .app folder and .ipa file would be inside the source folder, which doesn't seem right.

### ISSUE THREAD

**Issue by khronosX** [Microsoft/vsts-tasks#2145]
The Xcode Package task seems to assume that the relatives path to .app or .ipa file is from the sources folder. This seems to contradicts to what we want to do, which is to separate the sources folder and artifacts folder. Xcode build task allows the user to enter output folder manually. It doesn't seem right that the package task should assume that the .app folder will be inside the sources folder.

Also, Xcode build task allows the provisioning profile to be specified from relative path of the source. Xcode package seems to assume that the provisioning profile already exists and only take the name as the input. This seems to be inconsistent as well.

**Comment by bryanmacfarlane** [comment]
If you enter a relative path then it will be relative to the root of the repo.

But, you can enter non-relative paths in all the inputs (for example workFolder which is above repo) using variables

https://www.visualstudio.com/en-us/docs/build/define/variables

**Comment by khronosX** [comment]
That's the first thing I tried but it doesn't work.

Just for testing:
For path to .app, i put $(Build.SourcesDirectory)/test.

The task fails with:
error: Specified application doesn't exist or isn't a bundle directory : '/Users/cargokdk/agents/agent-1/_work/1/s/Users/cargokdk/agents/agent-1/_work/1/s/test/xxxxx.app'

As you can see, it's appending the path i have entered.

**Comment by bryanmacfarlane** [comment]
What's your vs.com account?  Or are you on prem?  I thought that was fixed awhile ago ...

**Comment by bryanmacfarlane** [comment]
Also confirm which version of the agent you are using.

**Comment by khronosX** [comment]
microsofthealth.visualstudio.com and agent is 10.11-x64-2.102.1.

The latest code on GitHub (https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/XcodePackageiOS/GenerateIpa.sh) still shows sourceDir being used.

**Comment by madhurig** [comment]
This is an old task that is using deprecated Xcode tools. It needs to be re-done to work with new toolset and handle working in both build and release definitions

**Comment by madhurig** [comment]
@khronosX: Which version of Xcode are you using? This task uses xcrun that has been marked deprecated since Xcode 7. Xcode 7 swift apps and WatchKit apps will not work with xcrun.

**Comment by madhurig** [comment]
Fix to allow task to run in Release builds in the current form (with xcrun): https://github.com/Microsoft/vsts-tasks/pull/2833

**Comment by madhurig** [comment]
The fix will be deployed to Team Services in early November.
