### ISSUE TITLE
Relase Definition variables vaule with secret cannot work

### ISSUE THREAD

**Issue by nickeyyan** [Microsoft/vsts-tasks#3216]
Hi VSTS team,

We have saved Database username and password in Variables, password saved as "secret". Previously, it works well. From today, if the password keep secret cannot work. If it saved as non-secret, it works. I believe it is a bug. Could someone to take a look?

Thanks,
Nickey

**Comment by rglos** [comment]
Can confirm this same thing just happened to us this morning.  A release using the `Azure SQL Database Deployment` task that has the Password property set to use a secret variable stopped working with the error:

`2016-12-08T16:52:41.9357464Z ##[error]Message        : No password specified for the SQL User: 'blahblah'`

I made the password variable non-secret, and the release worked again.

As an aside, this is the second time I've personally had a build or release fail because the underlying tasks get changed and a bug occurs.  I'm hoping that you have some E2E tests on your end that these tasks are getting cycled through before these get published and used by us, the wider audience.

**Comment by rglos** [comment]
I've now had a second release fail, not related to the `Azure SQL Database`, but this one uses `Powershell` script task.

We use the task to set the value of a variable in a web.config file.  The variable is a password and so we have that password in the release as a release variable then checked as a secret.

When I look at the web.config that was just deployed to that environment the value is blank.

So it appears this bug is not task specific but something with passing variables marked as secret to the tasks is not actually passing the variable value along but passing a empty string.

**Comment by ericsciple** [comment]
@kmkumaran do you know the status on this issue?

**Comment by ericsciple** [comment]
https://blogs.msdn.microsoft.com/vsoservice/?p=12915

**Comment by ericsciple** [comment]
...updates on that specific service issue are being posted there

**Comment by kmkumaran** [comment]
@rglos - The issue is addressed now. Can you try and let us know if you are unblocked.

**Comment by rglos** [comment]
I'm late to the game as I see you've closed this long ago but I was finally able to get around to testing this, and it is working correctly again with variables that are locked.  Thanks.

**Comment by OutKa5t** [comment]
Hi @kmkumaran we still have a couple of release definitions that I experience this issue. Is there anything we need to do or can do? 

Its worth mentioning that most secrets variables are now handled as expected and the issue only appears on a select few. Secret variables come through blank in the release initialisation e.g. [DBPWD] --> []

**Comment by chandan-anjani** [comment]
Hi @OutKa5t, you may re-enter the secret value for the failing one for now.  We may also try to fix it but for for that we may requires additional information e.g. account name (e.g. anjani.visualstudio.com), project name, release definition name for the failing one. Let me know, if you want us to  fix it.
