### ISSUE TITLE
Deployments Failing from VSO to AzureSql

### ISSUE THREAD

**Issue by dtmnash** [Microsoft/vsts-tasks#3454]
Our deployments from VSO hosted builds and release manager are failing as of this morning (1/18/17) at around 11 am. 

We are using the AutoDetect feature since our releases run on hosted servers. 

Error Message:
Unable to connect to master or target server 'XXXXX'. You must have a user with the same password in master or target server 'XXXXX'.

We are able to deploy using the same U/P as is configured in the Dacpactask from an IP range that is in our firewall.

**Comment by vincentdass** [comment]
@dtmnash, thanks for reporting the issue.
Can you verify that you have provided only the `username` in **Azure SQL Server Name** and not `username@servername` ?

You can see the actual commend running by enabling system.debug  = true before queuing the release.

**Comment by vincentdass** [comment]
@dtmnash , we fixed an related issue in SqlAzureDacpac task. Can you please queue a new release and check the task ?

**Comment by paonekumar** [comment]
@vincentdass @mvvsubbu we are still getting the issue, it is failing with the below error.

*** Could not deploy package.
Unable to connect to master or target server 'XXXX'. You must have a user with the same password in master or target server 'XXXX'.
Azure SQL Dacpac task failed. 

Removing @servername form user id fixed  in one environment, this fix is not working in all environments.

**Comment by mvvsubbu** [comment]
Can you share your username and server name formats for failing environments?

**Comment by dtmnash** [comment]
we are using just the username and password, not {username}@{servername}

**Comment by dtmnash** [comment]
The publishs work fine when using the same user/name password when going straight from visual studio sql database project

**Comment by mvvsubbu** [comment]
servername is something like xyz.database.windows.net? or xyz only? what is your account name?

**Comment by mvvsubbu** [comment]
Does your user name contains @ symbol? Can you share task debug logs by setting system.debug = true

**Comment by mvvsubbu** [comment]
Share your account name as well

**Comment by dtmnash** [comment]
VSTS Account is kiewitcorp.visualstudio.com 
[ReleaseLogs_329.zip](https://github.com/Microsoft/vsts-tasks/files/739337/ReleaseLogs_329.zip)

**Comment by mvvsubbu** [comment]
Your issue is not related to username/password issue. It is something related to firewall. Can you try suggestion given in thread https://social.msdn.microsoft.com/Forums/expression/en-US/0c70ce16-1dea-46a2-9ae0-8fe1d6237c49/azure-arm-sql-database-import-user-with-the-same-password-in-master-or-target-server-issue?forum=visualstudiogeneral 

In the Portal (portal.azure.com) Firewall Settings of the SQL Server there is an option called: "Allow access to Azure services". It was off. I activate it and is seems to work

**Comment by mvvsubbu** [comment]
The following is the command that runs on the automation agent. You can run by updating your password, to see whether servername/username/password which is going wrong.

"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130\SqlPackage.exe" /SourceFile:"D:\a\r1\a\Master.Deploy\Database\OPSM.Punchlist.Database.dacpac" /Action:Publish /TargetServerName:"asdbs-qa-scus-pun.database.windows.net" /TargetDatabaseName:"db-qa-scus-pun" /TargetUser:"N0j0bl0ss3s" /TargetPassword:"********"  /TargetTimeout:120

**Comment by mvvsubbu** [comment]
Can you update your status?

**Comment by mvvsubbu** [comment]
Any update?

**Comment by paonekumar** [comment]
@mvvsubbu appreciate your quick response, your suggestion worked and issue is fixed now.

**Comment by mvvsubbu** [comment]
Thanks for confirming I am closing the issue.
