### ISSUE TITLE
[Release Task] Deploy Azure App Service: XML Substitution unable to parse config

### ISSUE THREAD

**Issue by degant** [Microsoft/vsts-tasks#3575]
In the release task for azure app service deployment using the 3.0 template (in preview), the newly added XML substitution isn't able to parse the web.config.

Task: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureRmWebAppDeployment

Here's the trace from the release logs after enabling system.debug:
_Initiated variable substitution in config file : E:\agent_work\r69\a\temp_web_package_1627581922803074\Content\C\agent_work\157\s\src\project\obj\Release\Package\PackageTmp\Web.config
Detecting file encoding using BOM
Unable to parse file : E:\agent_work\r69\a\temp_web_package_1627581922803074\Content\C\agent_work\157\s\src\project\obj\Release\Package\PackageTmp\Web.config
**TypeError: listOfNodes.push is not a function**_

Task Version:
_Task         : Azure App Service Deploy
Description  : Update Azure App Service using Web Deploy / Kudu REST APIs
Version      : **3.0.5**_

**Comment by arjgupta** [comment]
Hi degant, can you please share your web.config file with RM_Customer_Queries@microsoft.com

**Comment by degant** [comment]
Sure will share it right away. Thanks!

**Comment by vincentdass** [comment]
@degant , the issue is resolved and the fix will be available in upcoming deployment.

**Comment by degant** [comment]
@vincentdass, @arjgupta What version will this be fixed in? And when will it be available?

**Comment by degant** [comment]
Hey I'm still waiting for a response. The fix is still not available in the preview. Do you have an ETA?

**Comment by arjgupta** [comment]
@degant  A fix for this issue has been deployed. Can you please verify if XMl substitution if working for you now.

**Comment by degant** [comment]
Hi @arjgupta thanks for the confirmation. After our conversation on mail I was under the impression that the fix is already deployed. Will check again in a week or two since the task is still showing up as 3.1.0 in our VSO.
