### ISSUE TITLE
Copy and Publish Build artifacts - Cannot bind argument to parameter 'StagingFolder' because it is null

### ISSUE THREAD

**Issue by jvalladolid** [Microsoft/vsts-tasks#3604]
Hi all.

I'm facing to the same problem that was posted here a month ago more or less. This is the thread that described the issue
https://github.com/Microsoft/vsts-tasks/issues/3392

In my case, I'm trying to upload the screenshots generated when there is an error running a functional test. I'm using a "Copy Publish Artifact" task inside a Release definition in VSO
![image](https://cloud.githubusercontent.com/assets/19993103/22922856/8eebf632-f29f-11e6-8c9d-81a20e03c098.png)

This is the log output with the error I'm getting:
`2017-02-13T17:37:08.2580667Z Executing the powershell script: C:\_ve\build_agent-v1\tasks\CopyPublishBuildArtifacts\1.0.30\CopyPublishBuildArtifacts.ps1
 
2017-02-13T17:37:08.3518178Z Preparing artifact content in staging folder ...
 
2017-02-13T17:37:08.3674418Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'StagingFolder' because it is null.
 
2017-02-13T17:37:08.3674418Z ##[error]   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
 
2017-02-13T17:37:08.3674418Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
 
2017-02-13T17:37:08.3674418Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
 
2017-02-13T17:37:08.3674418Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2017-02-13T17:37:08.3674418Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2017-02-13T17:37:08.3674418Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'LocalPath' because it is null.
 
2017-02-13T17:37:08.3674418Z ##[error]   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
 
2017-02-13T17:37:08.3674418Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
 
2017-02-13T17:37:08.3674418Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
 
2017-02-13T17:37:08.3674418Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)`

I don't now where the problem is :-(. I tried to change the Copy Root value, but same error.

How does this task work? How could I solve the issue?

Thanks in advance

**Comment by ericsciple** [comment]
The task is for builds only. I'll add a more graceful error in the task.

**Comment by iansul** [comment]
Are you saying that task won't work for a Release Definition? Is there any way to exclude it from the list of tasks you can add to release def.

**Comment by bryanmacfarlane** [comment]
There is a visibility setting in tasks.  Adding Sriram from the RM team to cover how to ensure some tasks don't show up in RM

@GitHubSriramB ?

**Comment by GitHubSriramB** [comment]
The only category of tasks that don't work with Release are the ones publishing artifacts. We didn't want to support visibility filter within Release just to filter out tasks of this category. Support for publishing artifacts within Release is in our backlog, but has not been prioritized yet.

**Comment by GitHubSriramB** [comment]
Until we have this support, we will fix "Copy and Publish" task to fail with a graceful error when used within Release.

**Comment by ericsciple** [comment]
Done :)
https://github.com/Microsoft/vsts-tasks/commit/4389fe909e29516168ef9c23a65e9f1ae39f1521

**Comment by troybooth** [comment]
Ah, no not done, this task still shows in RM and I get that exact error as stated by the OP....

**Comment by MoBattah** [comment]
Yeah, this is ridiculous. I can't believe that this is an issue. Don't show an incompatible task.
