### ISSUE TITLE
Deploy Test Agent v2.0.9 fails to start DTA as not all referenced dlls are in "TestExecution.zip"

### ISSUE THREAD

**Issue by NikolayKash** [Microsoft/vsts-tasks#4101]
Hello.

I just switched to 2.0.9 of this task from 1.0.42
DTA Version 

![image](https://cloud.githubusercontent.com/assets/8295880/25305396/15f8b648-2783-11e7-9615-9735c19179cc.png)
DTA log reports error:

DTAExecutionHost.exe Error: 0 : Main.InitializeAndStartExecutionHost. Exception occured during initialization/start: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.VisualStudio.TestService.VstestAdapter.DefaultTestRunEventHandler..ctor(String loggerIdentifier)
   at Microsoft.VisualStudio.TestService.VstestAdapter.SessionDetailStore..ctor() in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.VstestAdapter\SessionDetailStore.cs:line 23
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.ExecutionTaskStateModel..ctor(ITestExecutionServiceRestApiHelper restHelper, ExecutionTaskStateModelCompletedDelegate onCompletion, ITaskExecutor adapter) in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.AgentExecutionHost\ExecutionTaskStateModel.cs:line 55
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.ExecutionHost.Initialize(ITestExecutionServiceRestApiHelper restApiHelper) in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.AgentExecutionHost\ExecutionHost.cs:line 56
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.Program.InitializeAndStartExecutionHost() in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.AgentExecutionHost\Program.cs:line 66

full log: [DTAExecutionHost.exe.zip](https://github.com/Microsoft/vsts-tasks/files/949038/DTAExecutionHost.exe.zip)

Test agent 2017 was installed to C:\TestAgent2017\Common7\IDE\CommonExtensions\Microsoft\TestWindow without any issues 

OS: Windows 8.1 x32  industry pro

**Comment by erlendhalsteinli** [comment]
I have the same issue, when installing test agent on win 10 pro VM.

**Comment by NikolayKash** [comment]
I did a workaround and changed the path where DTAExecutionHost staff is installed to C:\TestAgent2017\Common7\IDE\CommonExtensions\Microsoft\TestWindow, now it works.

**Comment by erlendhalsteinli** [comment]
Thanks for the workaround, I have currently rolled back to v1 of the task.

**Comment by nigurr** [comment]
From the logs `VstestUtilities.FindTestWindowInstallDir VsSetupInstance is returning null`

Can you run this script and let us know the output `https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTest/vs15Helper.ps1`

**Comment by NikolayKash** [comment]
Hi. The output of the script is 

@nigurr 
PS C:\Users\admin> .\VS15Detect.ps1
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Nil />
</Objs>
PS C:\Users\admin\>

**Comment by nigurr** [comment]
@NikolayKash Can you please run this and let us know the output `vswhere.exe from https://github.com/Microsoft/vswhere/releases`

There seems to be broken TA 2017 installation in the machine.

**Comment by NikolayKash** [comment]
@nigurr 

`C:\Drop>vswhere.exe
Visual Studio Locator version 1.0.62 [query version 1.9.77.53636]
Copyright (C) Microsoft Corporation. All rights reserved.


C:\Drop>`

![image](https://cloud.githubusercontent.com/assets/8295880/25406043/0a64215e-2a0e-11e7-9249-1abd22e3da35.png)

if you like, I can share VStest Agent 2017 install logs

**Comment by nigurr** [comment]
@NikolayKash That would be helpful. Seems like Installation is not completed/failed . `SetupFinished=false`

**Comment by NikolayKash** [comment]
Hi @nigurr  

here we are 
[dd_setup_20170426043827.zip](https://github.com/Microsoft/vsts-tasks/files/957299/dd_setup_20170426043827.zip)

Hope I collected all of them from %temp% directory.

**Comment by nigurr** [comment]
@NikolayKash Can you restart your machine? and this should fix the issue `Closing installer. Return code: 3010.`

**Comment by NikolayKash** [comment]
@nigurr, i will, but deploy test agent task should do it, should not?

**Comment by nigurr** [comment]
@NikolayKash yes. it should. this has been taken care in recent commit https://github.com/Microsoft/vsts-tasks/pull/4059/files

**Comment by NikolayKash** [comment]
@nigurr  if I grab the latest state of master and replace a content under SBuildAgent\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\2.0.9 will it work?  all ps1  scripts

**Comment by nigurr** [comment]
@NikolayKash it will. but we strongly recommend you to wait for next Release cycle for On-Prem [TFS 2017 Update 2], or next deployment in VSTS.

Closing this thread as it's already fixed in master.

**Comment by NikolayKash** [comment]
@nigurr . 

I tried to run the test on 2.10  but it still fails.
```

2017-05-18T06:29:28.5420260Z Task         : Visual Studio Test Agent Deployment
2017-05-18T06:29:28.5420260Z Description  : Deploy and configure Test Agent to run tests on a set of machines
2017-05-18T06:29:28.5420260Z Version      : 2.0.10
2017-05-18T06:29:28.5420260Z Author       : Microsoft Corporation
2017-05-18T06:29:28.5420260Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=838890)
```

I tried to run tools which you specified.   I did a reboot of a machine and ps1 script shows the location, while vswhere does not

![image](https://cloud.githubusercontent.com/assets/8295880/26191782/eec51a46-3bb7-11e7-85ff-1dc755b2922f.png)

**Comment by nigurr** [comment]
@NikolayKash that's so weird. @Heaths, can we help out this customer?

**Comment by heaths** [comment]
@NikolayKash can you share what _vs.ps1_ is doing? Both clients rely on the same COM APIs. Also make sure that you do not have _Microsoft.VisualStudio.Setup.Configuration.Native.dll_ in the PowerShell module directory or where _vswhere_ is located. The newer code no longer loads directly, but if your module is older you might be using an older implementation.

**Comment by NikolayKash** [comment]
Hi @heaths  

vs.ps1 is https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTest/vs15Helper.ps1 

i used the latest vswhere.exe in my test above.

**Comment by heaths** [comment]
Because _vswhere_ by default looks only for VS SKUs. See Microsoft/vswhere#61 for details and solution.

**Comment by NikolayKash** [comment]
@HarishMS @nigurr.  So it did not work until I removed Agents 2013 and install manually Agents 2017 u2 in our VM. now deployment vstest agent task works like a charm. 

Thanks for your support.
