### ISSUE TITLE
Unable to parse JSON file in (JSON variable substitution)

### ISSUE THREAD

**Issue by etbuilder** [Microsoft/vsts-tasks#4884]
The task will fail with error  ##[error]Error: Unable to parse JSON file: PATH . Error: SyntaxError: Unexpected token / in JSON at position 63

We resolved the issue by removing comments from the JSON file any // was removed to fix the issue, the task should remove any comments before parsing.

**Comment by bryanmacfarlane** [comment]
Which task?  This issue has a few characters from a log with no context.

**Comment by etharreef** [comment]
Oh sorry, here is detais.

Task Deploy Azure App Service v3.0*

When using File Transforms & Variable Substitution Options --> JSON variable substitution with a json file that contains any inline comments (ie //bla bla bla)

The task will fail with ##[error]Error: Unable to parse JSON file: PATH . Error: SyntaxError: Unexpected token / in JSON at position 63

**Comment by elvirdolic** [comment]
We have the same issue with an comment in json file

**Comment by vincentdass** [comment]
@etharreef , @elvirdolic thanks for your feedback.
Currently the fix is in progress and update you once it's completed.

**Comment by ericbrunner** [comment]
When will that work in VSTS ?

**Comment by vincentdass** [comment]
@ericbrunner , we have the story in our backlog and will be taken based on the priority.
Will be updating the thread once the fix is deployed.

**Comment by shibinchandra** [comment]
is the fix implemented ?

**Comment by aleccaputo** [comment]
@shibinchandra it is not fixed.  We just ran into this today. Probably has something to do with string manipulating the JSON, and not taking the slashes in comments into consideration and parsing it as part of the JSON.

**Comment by SunnyOswal** [comment]
not fixed :(

**Comment by rswe** [comment]
Getting same issue today e.g. // style comments break VSTS Build  (using Task Azure Resource Group Deployment, rather than Appservice - please comment if I should raise a new separate incident?):

2018-01-07T22:13:06.4942880Z Resource Group created successfully.
2018-01-07T22:13:06.4946213Z Creating deployment parameters.
2018-01-07T22:13:06.5091189Z The detected encoding for file 'd:\a\1\s\mainTemplate.json' is 'utf-8'
2018-01-07T22:13:06.5365371Z ##[error]Error: Ensure the Template file ( 'd:\a\1\s\mainTemplate.json' ) is valid. Task failed while parsing with following error: Unexpected token / in JSON at position 49230

**Comment by vincentdass** [comment]
@rswe , please open a separate thread for this issue.

**Comment by sachinma** [comment]
@rswe can you specify the version of the Azure Resource Group Deployment task where you are seeing this behavior?

**Comment by rswe** [comment]
@sachinma  @vincentdass  Azure Resource Group Deployment task version 2.*
Raised in https://github.com/Microsoft/vsts-tasks/issues/6158

**Comment by vincentdass** [comment]
The Issue is resolved and the fix will be available in upcoming deployment.

**Comment by robk410** [comment]
Just ran into this on VSTS as of 3/30/2018. I had a comment in my appsettings.json. removed and now it works.

offending comment was a line that was removed from appsettings.json
...
// [ some config stuff ]
...

2018-03-30T17:40:37.7647836Z ##[section]Starting: IIS Web App Deploy
2018-03-30T17:40:37.7647836Z ==============================================================================
2018-03-30T17:40:37.7647836Z Task         : IIS Web App Deploy
2018-03-30T17:40:37.7647836Z Description  : Deploy a Website or Web Application using WebDeploy
2018-03-30T17:40:37.7647836Z Version      : 0.0.34
2018-03-30T17:40:37.7647836Z Author       : Microsoft Corporation
2018-03-30T17:40:37.7647836Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=866789)
2018-03-30T17:40:37.7647836Z ==============================================================================
2018-03-30T17:40:39.8585344Z XML variable substitution applied successfully.
2018-03-30T17:40:39.8897824Z ##[error]Error: Unable to parse JSON file: C:\...\appsettings.json. Error: SyntaxError: Unexpected token ] in JSON at position 1448
2018-03-30T17:40:39.9054101Z ##[section]Finishing: IIS Web App Deploy

**Comment by ongun23** [comment]
Having the same issiue.
