### ISSUE TITLE
PublishCodeCoverageResults is slow with many files in the generated report

### ISSUE THREAD

**Issue by octatone** [Microsoft/vsts-tasks#4945]
related: https://github.com/Microsoft/vsts-tasks/issues/1271

Hi there, we have a project whose coverage report (like the above closed issue) generates over 900 files as its HTML coverage summary output. The PublishCodeCoverageResults takes about as much time as it takes to generate the coverage report effectively doubling the time to complete our CI tasks. It takes over 2 minutes to publish our code coverage output (which in total is around 4MB).

Is it possible that the task is uploading each file one at a time? Can this be changed to zip the files (which are all text files), then upload the zip, and finally expand on the VSTS side?

**Comment by myarotskaya** [comment]
Hi there, is there any updates? I face this problem as well - it takes unacceptable long time to publish code coverage results.

**Comment by iwillspeak** [comment]
Seeing 1700+ files take over 3 minutes to publish. I'd really like to use the code coverage feature of pipelines but as it stands it's taking longer to publish the coverage than it takes to build and test our project.

We're able to upload far larger artifacts with the `publish:` yaml step in far less time (e.g. 140M in ~3s)

**Comment by matthoulb** [comment]
This is completely unusable.  We have a simple .NET Framework solution and this took 20 minutes until I gave up and cancelled it.  It was written 70mb+ HTML files for every single class and would have taken HOURS.

What is wrong with this?  It seems very broken.

**Comment by iwillspeak** [comment]
It would be nice to just publish coverage results like normal artifacts but have a way to mark up on the `publish` step that they should be used as coverage results. Normal `publish` steps are more than fast enough to upload.

**Comment by richardgavel** [comment]
Agree this is unusable. And it's because the code it uploading each file one at a time (not even doing multiple files in parallel)

https://github.com/microsoft/azure-pipelines-agent/blob/1500e376855708134b1662d17ceddfba9519f0ba/src/Agent.Worker/CodeCoverage/CodeCoveragePublisher.cs#L51

Couldn't this be changed to use the PipelineArtifactServer like the publish pipeline artifact task does?

https://github.com/microsoft/azure-pipelines-agent/blob/e80c3261724f3256141076ae666bd0ca47e267c7/src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV1.cs#L140

**Comment by DerAlbertCom** [comment]
This becomes more and more a problem. It's hard when to upload times takes over the build and test times. This is even worse on premises with the added latency.

**Comment by kachkaev** [comment]
Task performance is indeed disappointing. The task takes over three minutes for a project with ≈2K files. That’s about a third of how long the tests take to run 😞 Not much joy for PR authors and reviewers.

**Comment by ahaleiii** [comment]
Would like to echo what everyone else has said. Adding code coverage to our pipeline (.NET Core 2.1, coverlet.collector, cobertura) added 2 minutes to what was a 3 minute pipeline (1463 files). We will probably end up publishing just the .xml file as an artifact instead of as code coverage.

I don't suppose there is a way to publish a coverage file from one build to another..? Could create an async workflow:
- main build completes, coverage file is artifact
- second, generic build is triggered
- downloads coverage file from main build
- generates report and publishes coverage back to main build

**Comment by tldavies** [comment]
We have this problem where publishing the code coverage report increased the build by 50%. Disabling the autogenerate didnt help decrease the time. 

Currently to get around this we zip and upload the whole coverage report as an artifact of the build. Thus allowing engineers to access it. All of this takes less than a 1 minute. While publishing the coverage report(8500+ files) takes 10 minutes.

**Comment by kachkaev** [comment]
> Currently to get around this we zip and upload the whole coverage report as an artifact of the build.

Does this mean that you don’t have the Code Coverage tab in Azure UI and your devs need to download the archive?

**Comment by tldavies** [comment]
> > Currently to get around this we zip and upload the whole coverage report as an artifact of the build.
> 
> Does this mean that you don’t have the Code Coverage tab in Azure UI and your devs need to download the archive?

Yes, the devs have to download the report if they want more detail. We do have the Code Coverage tab in the Azure UI, it just empty. We do fail our builds for code coverage and the devs only care about the report when the builds fails.

**Comment by vviotto** [comment]
Adding my voice to this, code coverage is taking around 6 minutes to upload 649 files, we're going to remove this step because its really slowing down our pipeline.
![image](https://user-images.githubusercontent.com/73895378/115458056-9f83a480-a1fb-11eb-920f-99b6fd5b1cc0.png)

**Comment by danielpalme** [comment]
You can use the following approach to speed things up:

Generate coverage report with this task: https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator

Use the `PublishCodeCoverageResults` task only to publish the report and disable report regeneration.

Relevant YAML looks like this:
```yaml
variables:
  disable.coverage.autogenerate: 'true'

- task: reportgenerator@4
  inputs:
    reports: 'coverage.cobertura.xml'
    targetdir: 'coveragereport'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coveragereport/Cobertura.xml'
    reportDirectory: 'coveragereport'
```

**Comment by kachkaev** [comment]
@danielpalme We generate the report using `nyc` and `PublishCodeCoverageResults` only uploads files. Because it sends the files individually and not in the form of a single zip archive, the upload takes minutes. Each file is a separate HTTP request, so it’s >1K requests to make.

**Comment by elliot-nelson** [comment]
Huge +1 to this issue -- if this were task changes I'd happily put up a PR, but it seems like this might not be fixable without server-side changes.

In my case, although I only have about 1600 source files, it takes 1m30s to upload the Cobertura XML file and generated the coverage HTML; if I generate the HTML files myself with nyc and disable autogeneration as per the suggestion above, it takes _longer_ (2m30s) due to uploading all those generated HTML files individually.

I would really, really like "click into" HTML coverage reports from my builds for the developers, but not at that cost.  It seems like the workaround at this point might be uploading the files myself (maybe to an S3 bucket via s3 sync) and just linking to it from the Azure coverage report.

**Comment by peterdk** [comment]
Another +1, we just enabled coverage report, 3400 files, takes 5 min, for a build of 5 min, so not acceptable. Please make this a zip upload or so.

**Comment by elliot-nelson** [comment]
FWIW, for my company's monorepo (where we were having this problem), to get around this issue, at the end of our PR pipeline we are doing the following:

1. Generate (with `nyc`) all the HTML coverage output (and the combined, single-file Cobertura XML).
2. Use the CLI tool [azcopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10) to copy the HTML folder up to an Azure Blob Storage container.
3. Generate a new, tiny HTML file that is just a link to the newly created `index.html` in Azure Blob Storage.
4. Now use the standard `PublishCodeCoverageResults@1` Azure task, but it only uploads the single XML file and the tiny HTML file we generated in Step 3.

At around ~2000 covered source files (and thus 2000 HTML files), these steps take:

1. 3 seconds
2. 2 seconds
3. 0 seconds
4. 2 seconds

So under 10 seconds for what was taking over 3 minutes.

(I'm throwing this out there mostly to show the kinds of lengths people need to go to when really the task itself could be fixed to use `azcopy` under the hood.  It's also a possible workaround for other folks out there, although the task of correctly configuring the Azure Blob Storage, authenticating it so your developers can reach it and view the coverage reports, getting the Azure creds into your pipeline, it's all a real hassle.)

**Comment by kadian1470** [comment]
Has there been any updates around zipping these files yet?

**Comment by jsiegmund** [comment]
Another +1 from our side, we're having the exact same problem. Uploading the results takes up about 50% of our total build time (around 12 minutes). So cutting this down would make a huge difference and does not seem to be that hard. There really should be a way to upvote these issues btw, give some sort of feedback as to how many community members need something to be fixed (I also understand this would not necessarily be the same priority as the product team has).

**Comment by anatolybolshakov** [comment]
@nadesu @ganesp could you please take a look?

**Comment by MatiSanchez** [comment]
Any updates??

**Comment by blogcraft** [comment]
I also find uploading the code coverage result to be extremely slow making me even considering to remove it.

**Comment by a1i3n37** [comment]
I would like to add my voice here as well. 

The task takes minutes to complete. Is there any update on this issue? Simply throwing the files in a package and uploading it as a single file and unpacking on the other end should fix this issue. The package doesn't even need to be compressed (though, that would be nice as well). 

At the current state, I am also considering in disabling this feature, because it is unusably slow.

**Comment by PeetersJeroen** [comment]
We have moved code coverage results to a dedicated build because it takes so long, hoping it will be fixed eventually

**Comment by Nodnarb3** [comment]
How is this thread over 5 years old and this is still an issue?? hello?

**Comment by blogcraft** [comment]
Nothing yet?

**Comment by brianpham93** [comment]
It's still very slow as of today

**Comment by MatteoSp** [comment]
It's 6 years now...

**Comment by andreypopov** [comment]
+1 too slow )

**Comment by bart-medfar** [comment]
Really slow, did any of you got an alternative running ?

**Comment by Pentadome** [comment]
ignore game is strong

**Comment by basit1327** [comment]
PublishCodeCoverageResults randomly skip last few files after few minutes  as a result no html report on available on Azure DevOps tab.
<img width="724" alt="Screenshot 2023-10-17 at 11 28 33 AM" src="https://github.com/microsoft/azure-pipelines-tasks/assets/27570442/661f38d5-ba40-4014-b012-fa19fcc72425">

<img width="724" alt="Screenshot 2023-10-17 at 11 29 19 AM" src="https://github.com/microsoft/azure-pipelines-tasks/assets/27570442/4af98f3e-cda0-4321-8b3f-3a63687da6db">

**Comment by ptemmer** [comment]
Adding this parameter made it work for me:
`DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeByAttribute=GeneratedCodeAttribute`

**Comment by Oldervoll** [comment]
+1, please improve!

**Comment by blogcraft** [comment]
Looks like no contributor cares about this.

**Comment by tripleacoder** [comment]
I have this problem too, uploading 1754 files takes 2:36 minutes.

**Comment by andreypopov** [comment]
resolved with task v2

PublishCodeCoverageResults@2

**Comment by tripleacoder** [comment]
> resolved with task v2
> 
> PublishCodeCoverageResults@2

OK, good to hear. 
Unfortunately, PublishCodeCoverageResults@2 does not support detailed code coverage reports, it only shows a short summary.

**Comment by chrisarmand** [comment]
> PublishCodeCoverageResults randomly skip last few files after few minutes as a result no html report on available on Azure DevOps tab. <img alt="Screenshot 2023-10-17 at 11 28 33 AM" width="724" src="https://private-user-images.githubusercontent.com/27570442/275732091-661f38d5-ba40-4014-b012-fa19fcc72425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDY4OTcsIm5iZiI6MTcyNDI0NjU5NywicGF0aCI6Ii8yNzU3MDQ0Mi8yNzU3MzIwOTEtNjYxZjM4ZDUtYmE0MC00MDE0LWIwMTItZmExOWZjYzcyNDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEzMjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNjBmZTIzNmUwNjFhMzJlOGJmMmM2ZWVhYjM4MzM2MjBmNGEzMTVhZGVkN2NkZTJiODhlYzEzMGVkYmI2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eMrq-x9U3hrYgQRVENigpy12a0BxQv-JVcHo0BGdo8c">
> 
> While for task where files are less then 500 it work fine <img alt="Screenshot 2023-10-17 at 11 28 33 AM" width="724" src="https://camo.githubusercontent.com/36a46f75ffdc88fa3e8b003b36e63a45df3c05a6621c388fb45912874c82f153/68747470733a2f2f692e6962622e636f2f677967664c536a2f53637265656e73686f742d323032332d31302d31372d61742d31312d33312d30312d414d2e706e67">

seems there is a 2min timeout on underling CoveragePublisher.Console
see https://github.com/microsoft/azure-pipelines-coveragepublisher/blob/master/src/CoveragePublisher/ArgumentsProcessor.cs
![image](https://github.com/user-attachments/assets/f73175b6-3c4d-4d7c-9d69-d290b4e1f591)

unfortunately, AzDevOps task wrapping CoveragePublisher.Console does not seem to handle this `timeout` parameter
see https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/coveragepublisher/coveragepublisher.ts

**Comment by victorgomezdejuan** [comment]
Hi there, we were facing the same issue and finally found a way to check the percentage of the code coverage and publish the report in less than 4 seconds (it took over 2 minutes before).

This is what we had (over 2 minutes):
```
- task: reportgenerator@5
    displayName: "Generate Reports"
    inputs:
      reports: '$(Build.SourcesDirectory)\**\*.Cobertura.xml'
      targetdir: '$(Build.SourcesDirectory)\coverlet\reports'
      reporttypes: 'HtmlInline_AzurePipelines_Dark;Cobertura'

  - task: JakubRumpca.azure-pipelines-html-report.PublishHtmlReport.PublishHtmlReport@1
    displayName: "Publish Unit Tests Report"
    inputs:
      reportDir: '$(Build.SourcesDirectory)\coverlet\reports\index.html'

  - task: PublishCodeCoverageResults@2
    displayName: "Publish Code Coverage Report"
    inputs:
      summaryFileLocation: '$(Build.SourcesDirectory)\coverlet\reports\Cobertura.xml'
      failIfCoverageEmpty: true  

  - task: BuildQualityChecks@9
    displayName: "Code coverage quality check"
    inputs:
      checkCoverage: true
      coverageFailOption: 'fixed'
      coverageType: 'lines'
      coverageThreshold: '85.5'
```

And this what we have now (less than 4 seconds):
```
  - task: reportgenerator@5
    displayName: "Generate code coverage report"
    inputs:
      reports: '$(Agent.TempDirectory)/*/*.cobertura.xml'
      targetdir: '$(Build.SourcesDirectory)\code-coverage-report'
      reporttypes: 'HtmlInline_AzurePipelines_Dark;Cobertura'
      riskhotspotassemblyfilters: '-*'
      customSettings: 'minimumCoverageThresholds:lineCoverage=85'

  - task: JakubRumpca.azure-pipelines-html-report.PublishHtmlReport.PublishHtmlReport@1
    displayName: "Publish code coverage report"
    condition: always() 
    inputs:
      reportDir: '$(Build.SourcesDirectory)\code-coverage-report\index.html'
      tabName: 'Code Coverage (Complete)'
```

The actual leverage point was using the _customSettings_ property of _reportgenerator@5_ task, so that we did not need to publish the "standard" coverage report to be able to check the code coverage percentage.

I hope this help you as well.

**Comment by danielpalme** [comment]
@victorgomezdejuan 
You could further simplify your build process by using the setting `publishCodeCoverageResults: true`

```yaml
  - task: reportgenerator@5
    displayName: "Generate code coverage report"
    inputs:
      reports: '$(Agent.TempDirectory)/*/*.cobertura.xml'
      targetdir: '$(Build.SourcesDirectory)\code-coverage-report'
      reporttypes: 'HtmlInline_AzurePipelines_Dark;Cobertura'
      riskhotspotassemblyfilters: '-*'
      customSettings: 'minimumCoverageThresholds:lineCoverage=85'
      publishCodeCoverageResults: true
```

**Comment by danielpalme** [comment]
@victorgomezdejuan 
You are right, the "official" Code coverage tab blocks all Javascript and therefore does not have all features available.  
I wasn't aware of the `JakubRumpca.azure-pipelines-html-report.PublishHtmlReport.PublishHtmlReport` extension. Thanks for that!

**Comment by rrussell0** [comment]
The upload step of this task still takes way, way too long. I'm giving it a simple XML and it matches files back to the source directory fairly quickly (~20 sec) but the upload is about 2 minutes. This is with 1400~ files, being run from a Microsoft hosted agent.

**Comment by rrussell0** [comment]
Can this be reopened? This task is still extremely slow.
