### ISSUE TITLE
AzureCLI task is unable to find Python

### ISSUE THREAD

**Issue by mivano** [Microsoft/vsts-tasks#5077]
Trying to run a build with a simple Azure CLI task. Task is set to inline script with as contents **az vm list**. When run on a Hosted VS2017 agent, it indicates it cannot find Python (##[error]Script failed with error: 'python' is not recognized as an internal or external command,).

![image](https://user-images.githubusercontent.com/668535/29540081-08eccf3a-86cd-11e7-8aea-7eedf656bc4e.png)

A couple of days ago this seemed to work fine. Any pointers what I can do to get this to work?

**Comment by melborp** [comment]
I am also hitting it. Azure CLI is a core part of the azure deployment, and this is blocking all releases currently.

**Comment by MattiasHognas** [comment]
Same error here, our full CI/CD is in VSTS hosted agents..

**Comment by rgovardhms** [comment]
We are looking into this issue. Will update after the investigation. 
Thanks!

**Comment by a135009** [comment]
Same same. The hosted and linux preview also fail with:
`2017-08-22T22:14:29.4776390Z ##[error]Unhandled: Failed which: Not found az: null
`

**Comment by mivano** [comment]
Is there any update on this issue? Or should we raise a formal case with MS so it can be picked up?

**Comment by melborp** [comment]
We added azure powershell based scripts as alternative, unfortunately swapping using azure powershell is way slow compared to azure cli. But it works as alternative until the image gets fixed.

**Comment by sachinma** [comment]
You can install az cli just in time by adding powershell task  with following inline script in your build/release process on VS2017 pool. This will ensure that Azure CLI task will work:

&'C:\Program Files\Python36\python.exe' -m pip install --user azure-cli
Write-host '##vso[task.prependpath]C:\Program Files\Python36\'

**Comment by iyerusad** [comment]
@sachinma thank you for the workaround. Pretty crappy this is a thing.

![image](https://user-images.githubusercontent.com/25647368/29639580-75c2715e-8818-11e7-9b77-df4fcd8a75d1.png)

**Comment by mivano** [comment]
Adding the powershell step will get met an Azure CLI on the Hosted 2017 agents. Cannot run the shell scripts, so had to convert to batch. Would be nice if this works out of the box and with the Linux agents.

**Comment by rgovardhms** [comment]
The issue is fixed now.

Thanks!

**Comment by mivano** [comment]
Working fine now. Thanks!

**Comment by davidobrien1985** [comment]
I'm still getting this error with the Hosted Linux agent.

Plus, using NPM to install the CLI gives me hundreds of permission errors.

@rgovardhms can you check this for Linux please?

**Comment by davidobrien1985** [comment]
This is what I'm getting over and over again:

```
2017-09-02T14:24:29.9816060Z [command]/usr/local/bin/npm install -g azure-cli
2017-09-02T14:24:33.6505210Z npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
2017-09-02T14:24:33.8194810Z npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
2017-09-02T14:24:43.5760210Z /usr/local/bin/azure -> /usr/local/lib/node_modules/azure-cli/bin/azure
2017-09-02T14:24:43.5949570Z 
2017-09-02T14:24:43.5966640Z > fibers@1.0.15 install /usr/local/lib/node_modules/azure-cli/node_modules/fibers
2017-09-02T14:24:43.5983380Z > node build.js || nodejs build.js
2017-09-02T14:24:43.5991360Z 
2017-09-02T14:24:45.1181110Z gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.2.1"
2017-09-02T14:24:45.1213800Z gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/azure-cli/node_modules/fibers/.node-gyp"
2017-09-02T14:24:45.1321730Z gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/usr/local/lib/node_modules/azure-cli/node_modules/fibers/.node-gyp/8.2.1"
2017-09-02T14:24:45.1341570Z gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/azure-cli/node_modules/fibers/.node-gyp"
2017-09-02T14:24:45.1406590Z gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/azure-cli/node_modules/fibers/.node-gyp/8.2.1"
2017-09-02T14:24:45.1454440Z gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/azure-cli/node_modules/fibers/.node-gyp"
```

**Comment by davidobrien1985** [comment]
Okay, was able to hack something together...

```
apt-get update -y && apt-get install -y python libssl-dev libffi-dev python-dev build-essential
curl -L https://azurecliprod.blob.core.windows.net/install.py -o install.py
printf "/usr/azure-cli\n/usr/bin" | python install.py
az
```

**Comment by sachinma** [comment]
@davidobrien1985 az tool was never available on Hosted Linux Agent. Consider opening a new issue as enhancement to track installing az in the Hosted Linux Agent.

**Comment by davidobrien1985** [comment]
Okay, no worries, but npm is, right?
My problem actually looks more like an npm issue.

Sent from my iPhone

On 4 Sep 2017, at 3:27 am, Sachin Mangla <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidobrien1985<https://github.com/davidobrien1985> az tool was never available on Hosted Linux Agent. Consider opening a new issue as enhancement to track installing az in the Hosted Linux Agent.

**Comment by jainr** [comment]
I am getting a similar error where VSTS Hosted Linux Preview agent does not come pre-installed with az cli. Is downloading it from within the script the recommended workaround?

**Comment by iyerusad** [comment]
@jainr It appears per comment https://github.com/Microsoft/vsts-tasks/issues/5077#issuecomment-326818748 that `az cli` is NOT currently included as part of the Hosted Linux Agent Preview.

To workaround, I was able to use the steps outlined by @davidobrien1985 here: https://github.com/Microsoft/vsts-tasks/issues/5077#issuecomment-326750491. This works as expected and allows Azure CLI tasks to run on the Hosted Linux Agent.
