### ISSUE TITLE
powershell task should now prefer `pwsh` on mac/linux

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-tasks#5894]
The executable has changed now for powershell core to `pwsh` instead of `powershell`, even on Windows. On Mac/Linux we should definitely prefer pwsh and fallback to powershell for back-compat. On Windows, I think we should just try `powershell` since I'm not sure why that wouldn't be in the PATH and preferring pwsh seems incorrect.

**Comment by mrvladis** [comment]
I have used the following Shell script in front of PowerShell one as workaround:
#!/bin/bash
ln -s /usr/bin/pwsh /usr/bin/powershell

**Comment by fredgate** [comment]
Error occurs on vsts for build process using the _powershell 2.* preview_ task when executed on _Hosted Linux Preview_ queue.
The error message is : 
```
2018-01-07T01:02:09.9877435Z ==============================================================================
2018-01-07T01:02:09.9892222Z Task         : PowerShell
2018-01-07T01:02:09.9904716Z Description  : This is an early preview. Run a PowerShell script on Windows, macOS, or Linux.
2018-01-07T01:02:09.9919812Z Version      : 2.125.0
2018-01-07T01:02:09.9932931Z Author       : Microsoft Corporation
2018-01-07T01:02:09.9947697Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2018-01-07T01:02:09.9960222Z ==============================================================================
2018-01-07T01:02:10.2884780Z Generating script.
2018-01-07T01:02:10.3027277Z ##[error]Unable to locate executable file: 'powershell'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

What to do ?

**Comment by mrvladis** [comment]
@fredgate  see my comment above.

**Comment by ericsciple** [comment]
fixed in master https://github.com/Microsoft/vsts-tasks/pull/6175

will roll out with the next deployment. the next deployment starts next week and will roll out over a week or two.

**Comment by AceHack** [comment]
@ericsciple I'm still getting the error above on the hosted linux agent

https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/16.04/standard/Dockerfile

Any idea when I should see it working?

Thanks.

**Comment by ericsciple** [comment]
I would expect the change to make it to most, if not all public scale units by the end of this week.

**Comment by ericsciple** [comment]
the deployment hasn't progressed beyond the first ring of accounts yet (all internal accounts).

**Comment by corretge** [comment]
I have the same issue but in Windows Server 2016. After installed PowerShell Core 6.0.2 and added it in PATH, VSTS still executing powershell.exe instead pwsh.exe.

**Comment by bryanmacfarlane** [comment]
@corretge - are you use TFS or VSTS?

**Comment by corretge** [comment]
@bryanmacfarlane VSTS cloud

**Comment by bryanmacfarlane** [comment]
@corretge - are you using the 2.x version of the task?  The fix is in 2.0:  https://github.com/Microsoft/vsts-tasks/pull/6175/files

**Comment by corretge** [comment]
Lots of thanks @bryanmacfarlane for the info.

visualstudio.com has version 2.0.3.

It works with Linux agents, but not yet with Windows agents.

**Comment by dhabierre** [comment]
I have the same issue with Azure DevOps / Agent Ubuntu 18.04 / Azure Powershell Task

```
2019-12-12T15:12:26.8377756Z ##[debug]which 'pwsh'
2019-12-12T15:12:26.8387401Z ##[debug]not found
2019-12-12T15:12:26.8389194Z ##[debug]which 'powershell'
2019-12-12T15:12:26.8392524Z ##[debug]not found
2019-12-12T15:12:26.8395178Z ##[debug]which 'pwsh'
2019-12-12T15:12:26.8398130Z ##[debug]not found
2019-12-12T15:12:26.8401619Z ##[debug]task result: Failed
2019-12-12T15:12:26.8478727Z ##[error]Unable to locate executable file: 'pwsh'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Powershell installation**

```
sudo snap install powershell --classic
```

**which pwsh**

```
/snap/bin/pwsh
```

**echo $PATH**

```
/home/admin-vm/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**ll /snap/bin**

```
lrwxrwxrwx 1 root root   13 Dec 12 14:59 powershell -> /usr/bin/snap*
lrwxrwxrwx 1 root root   10 Dec 12 14:59 pwsh -> powershell*
```

Any idea?
Thanks!

**Comment by dhabierre** [comment]
I've found my problem.

I am using Terraform to create and setup a Linux agent with the **remote-exec** provisionner:

```hcl
provisioner "remote-exec" {
  inline = [
    # Powershell
    # --------------------------------------------------------------------------------
    "sudo snap install powershell --classic",
    "sudo pwsh -NoLogo -NoProfile -NonInteractive -Command Install-Module PowerShellGet -Repository PSGallery -Force",
    "sudo pwsh -NoLogo -NoProfile -NonInteractive -Command Install-Module Az -AllowClobber -Force",
    # Azure DevOps Agent
    # --------------------------------------------------------------------------------
    "mkdir agent && cd agent",
    "wget https://vstsagentpackage.azureedge.net/agent/2.163.1/vsts-agent-linux-x64-2.163.1.tar.gz",
    "tar zxvf ./vsts-agent-linux-x64-2.163.1.tar.gz",
    "./config.sh --unattended --url ${var.serverUrl} --auth pat --token ${var.pat} --pool ${var.agentPool} --agent ${azurerm_virtual_machine.virtualmachine[count.index].name}",
    "sudo ./svc.sh install && sudo ./svc.sh start"
  ]
```
When executing the **./config.sh** command, the file **.path** is created with the current $PATH and it is used to setup the PATH capability. But but the path does not contains **/snap/bin* folder!

And thus the _Azure Powershell Task_ failed with **which pwsh => not found**.

=> set the PATH before executing ./config.sh:

```hcl
provisioner "remote-exec" {
  inline = [
    # Powershell
    # --------------------------------------------------------------------------------
    <...>
    # Azure DevOps Agent
    # --------------------------------------------------------------------------------
    "mkdir agent && cd agent",
    "wget https://vstsagentpackage.azureedge.net/agent/2.163.1/vsts-agent-linux-x64-2.163.1.tar.gz",
    "tar zxvf ./vsts-agent-linux-x64-2.163.1.tar.gz",
    # *******************************************************************************************
    "export PATH=\"$PATH:/snap/bin\"",
    # *******************************************************************************************
    "./config.sh --unattended --url ${var.serverUrl} --auth pat --token ${var.pat} --pool ${var.agentPool} --agent ${azurerm_virtual_machine.virtualmachine[count.index].name}",
    "sudo ./svc.sh install && sudo ./svc.sh start"
  ]
```
