### ISSUE TITLE
Offline test agent deployment error

### ISSUE THREAD

**Issue by darkcite** [Microsoft/vsts-tasks#5969]
## Environment
-    TFS 2017 U2
-    Windows on agent machine: Windows server 2012R2 (with internet access)
-    Windows on target test agent deployment machine: Windows server 2012R2 (no internet access)
-    Agent Version: 2.117.2

## Issue Description

I'm creating a clean VM with Windows server 2012R2 using a default iso downloaded from my MSDN subscription then trying to deploy test agent from offline installer and then run tests on it. Within the first attempt to deploy it I'm getting an error from the first log. If I'll rerun deploy test agent step again it will be completed successfully but then test execution will fail with the error as it is in the DTA logs attached.
I've tried to use offline installer created as described in https://aka.ms/testagentlocation and also created by the direct execution of Start-OfflineProcess from https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployVisualStudioTestAgent/CreateOfflineTestAgent.ps1 and for all cases I've got the same result.

P.S. Fix suggested in https://github.com/Microsoft/vsts-tasks/issues/5927 by @nigurr did not help and failed with the same results.

### Error logs
[4_Deploy TestAgent on GASAPP01DV (1).log](https://github.com/Microsoft/vsts-tasks/files/1505936/4_Deploy.TestAgent.on.GASAPP01DV.1.log)

[4_Deploy TestAgent on GASAPP01DV (2).log](https://github.com/Microsoft/vsts-tasks/files/1505931/4_Deploy.TestAgent.on.GASAPP01DV.2.log)

[DTAExecutionHost.exe.log](https://github.com/Microsoft/vsts-tasks/files/1505937/DTAExecutionHost.exe.log)

**Comment by nigurr** [comment]
@darkcite Sorry for the trouble. The issue `Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))` is fixed in 2018 RTM.

Can you please add the following line to `Start-Sleep -Seconds 60 # required to keep service active till process loads Assembly_Resolve` https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployVisualStudioTestAgent/TestAgentConfiguration.ps1#L152 in your Build agent machine `[C:\BuildAgent\_work\_tasks\DeployVisualStudioTestAgent\xxxxxx\TestAgentConfiguration.ps1]`

**Comment by hegsie** [comment]
Officially giving up on this ever working, time to roll our own version, its not worked since TFS 2015, tested in 2018 and still doesn't work grrr

**Comment by nigurr** [comment]
@hegsie We will help you to fix the issue and understand any issue which is not addressed in our feature implementation. Can you please drop us your skype id at devops_tools at microsoft dot com.
or please reach us through Microsoft Support tool https://support.microsoft.com/

**Comment by darkcite** [comment]
@nigurr just tested this issue on TFS 2018 with the latest version of vnext agent and task and problem is still the same.

**Comment by hegsie** [comment]
I tried emailing devops_tools at microsoft dot com however I just get...

Generating server: BN6PR21MB0162.namprd21.prod.outlook.com
tri@microsoft.com
Remote Server returned '< #5.7.133 smtp;550 5.7.133 RESOLVER.RST.SenderNotAuthenticatedForGroup; authentication required; Delivery restriction check failed because the sender was not authenticated when sending to this group>'

**Comment by nigurr** [comment]
@hegsie we received your mail and will respond back.

**Comment by nigurr** [comment]
@darkcite Can you please add small change in your Build agent folder `(C:\BuildAgent\_work\_task\DeployVisualStudioTestAgent\xxxxx\TestAgentConfiguration.ps1)` -> https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployVisualStudioTestAgent/TestAgentConfiguration.ps1#L152

This should fix the issue. If you are still facing an issue, please do share fresh DTAExecutionHost.exe logs

**Comment by darkcite** [comment]
@nigurr After implementing your fix situation is the following:
First execution of Deploy Test Agent task fails with:
[11_Deploy TestAgent on GASAPP01DV.log](https://github.com/Microsoft/vsts-tasks/files/1543121/11_Deploy.TestAgent.on.GASAPP01DV.log)
But if after that failure restart target machine and then try to execute Deploy Test Agent task once more - it completes successfully and tests are running in a normal way.

**Comment by nigurr** [comment]
Closing this issue as these are fixed in subsequent TFS releases.
