### ISSUE TITLE
Download Build Artifacts task for specific build dropdowns are empty

### ISSUE THREAD

**Issue by goldenbeard** [Microsoft/vsts-tasks#7355]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
VSTS environment, account: aecom.visualstudio.com
Attempted in a couple of team projects: Digital Transformation - CS and Digital Transformation - DPC.
Also tried in several build/release definitions, the behaviour is the same.

## Issue Description

When configuring the "Download Build Artifacts" task (I believe it's version 0.136.1) I am unable to set either the project or build definition when selecting to download the artifacts produced by a 'specific build'. Both dropdowns are not displaying, or very briefly show a narrow (empty) dropdown. As a result I'm unable to progress any further with the configuration.

### Error logs

Checking the browser developer settings, it looks like the requests to VSTS to collect the data for populating the dropdowns are failing:

POST: https://aecom.visualstudio.com/b7d1a893-2e60-46c4-839b-8e0b352c9b96/_apis/serviceendpoint/endpointproxy?endpointId=tfs%3A00025394-6065-48CA-87D9-7F5672854EF7
with payload:
{"serviceEndpointDetails":null,"dataSourceDetails":{"dataSourceUrl":"{{endpoint.url}}/_apis/projects?$skip={{skip}}&$top=1000","resourceUrl":"","requestContent":"","requestVerb":"","parameters":{},"resultSelector":"jsonpath:$.value[?(@.state=='wellFormed')]"},"resultTransformationDetails":{"resultTemplate":"{ \"Value\" : \"{{{id}}}\", \"DisplayValue\" : \"{{{name}}}\" }","callbackContextTemplate":"{\"skip\": \"{{add skip 1000}}\"}","callbackRequiredTemplate":"{{isEqualNumber result.count 1000}}"}}

returns a 400 error with the response body:
{"$id":"1","innerException":null,"message":"One or ore of the fields needed for pagination support are missing. Provide all of the required fields.","typeName":"Microsoft.TeamFoundation.DistributedTask.WebApi.InvalidServiceEndpointRequestException, Microsoft.TeamFoundation.DistributedTask.WebApi","typeKey":"InvalidServiceEndpointRequestException","errorCode":0,"eventId":3000}

I have saved a copy of a HAR showing the failed requests if you wish me to send them over.

**Comment by DerGary** [comment]
We currently have the exact same Problem

**Comment by omeshp** [comment]
@goldenbeard @DerGary We have hot fixed this issue, can you confirm that this is resolved?

**Comment by goldenbeard** [comment]
@omeshp Yes I can confirm that the project and build selectors are now working.

I'm still not getting anything appearing in the 'specific' artifact droplist but this doesn't seem to be due to an error and I'm able to type in the name of the artifact to get the task running correctly in my build.

Thanks for the fast fix :)

**Comment by omeshp** [comment]
Thanks @goldenbeard for confirmation. 

Also 'specific' artifact droplist only works if the "Build version to download" is "Specific Version".
