### ISSUE TITLE
Missing attachments in test result from vstest task

### ISSUE THREAD

**Issue by NingPing** [Microsoft/vsts-tasks#7685]
## Environment
VSTS
private agent
windows 10
visual studio 2015
mstest

build steps
nuget restore
build solution
vstest (with the Upload test attachments checked)

## Issue Description
I run suite of selenium test and usually attach the screenshot as described by this article 
[https://docs.microsoft.com/en-us/vsts/test/collect-screenshots-and-video?view=vsts](url)
and it was working fine until a couple of weeks ago. Now attachment is always empty.

Ive tried running with a minimal setup with both visual studio 2015 and 2017 an single testmethod but  attachments are always empty, any help with be appreciated.

**Comment by nmohammad1** [comment]
I have the same issue. I am using TestContext. AddResultFile. Not sure when it broke but it was working fine when I executed last month and I executed tests yesterday and it is not showing attachments on any of the test cases now. 
I am using

VSTS
Private Agent
Windows 10
Visual Studio 2015
MSTest
![attachmentsmissing](https://user-images.githubusercontent.com/28737978/42822806-f5e6de36-89a9-11e8-8925-a2d6c39f43a3.jpg)

**Comment by NingPing** [comment]
@nmohammad1 Yes exactly the same issue, thank you for filling in with more information and confirming im not alone.

**Comment by nigurr** [comment]
Can you please share your build/release logs with `system.debug=true`?

**Comment by nmohammad1** [comment]
Hi Nitin,

You probably got this from Github. I had also raised a ticket. A support specialist from MSFT spoke to me and told me the issue has been resolved. I do see attachments now. Thanks for getting back to me.

Thanks
Nawaz

**Comment by NingPing** [comment]
@nigurr yes can also confirm something has changed but for me its only partially resolved i can now see 1 of 2 attachment, i believe theres still an issue with multiple attachment.
@nmohammad1  do you know what they did and is there something i can do on my side?

**Comment by nigurr** [comment]
@NingPing, rerunning with multiple iterations and attachments is on the way. It's only applicable in the Build/Release hub. Closing this issue.

![image](https://user-images.githubusercontent.com/15208679/43441518-a91cdd34-94b8-11e8-9133-b825222f2dd4.png)
