### ISSUE TITLE
Azure App Service Deploy 4.* Error: "File not found in Kudu Service. script_result.txt"

### ISSUE THREAD

**Issue by BenBrooksCin7** [Microsoft/vsts-tasks#7694]
## Environment

- Environment: [VSTS](https://cin7.visualstudio.com/Cin7/_release?releaseId=6165&_a=release-logs)

- Agent: Hosted agent, queue name: "Hosted VS2017"

## Issue Description

We have 2 existing deploys to 2 different Azure websites, each site also has another site in a Virtual application. As of around time 2018-07-10T23:30:00 the deployment to the root site was still working fine, but deployments to the Virtual application (which step is directly after) started failing. Neither definition nor site was updated around the time of the failure. There was another build around 2 hours earlier which completed just fine.

I'm guessing that around that time, [change #7438](https://github.com/Microsoft/vsts-tasks/commit/fe563fa3f5eb72ee15f4cf05f4c7794a1d47153d#diff-97234713bef5cd2238759849137bda8c) went live and I think the error is on line 63 as it uses a partially hard coded path which is then not used when the file is read on line 262.

We have since updated the deploy to use Azure App Service Deploy 3.* and it deploys without issue.

As part of this deploy step, a post deployment action inline script is executed. Unsure if this contributes to the above issue or not. There is also a post deployment action inline script on the previous step that deploys to the root site without issue.

### Error logs

2018-07-10T23:33:27.2761084Z Executing given script on Kudu service.
2018-07-10T23:33:32.9258596Z ##[error]Error: Unable to run the script on Kudu Service. Error: Error: File not found in Kudu Service. script_result.txt

**Comment by vincentdass** [comment]
@BenBrooksCin7 , thanks for reporting the issue and identifying the cause.
It's a genuine issue and will be fixed in upcoming deployment.

**Comment by vincentdass** [comment]
The issue is fixed and the fix is available in all accounts.

**Comment by rand0me** [comment]
I'm still experiencing this issue while deploying Azure Function App with any post-deployment command

**Comment by vincentdass** [comment]
@rand0me , can you share the task version and the debug logs (set variable `system.debug` to `true` and requeue a release)?

**Comment by vincentdass** [comment]
@rand0me .
Currently, we dont have first class support for Linux function apps (exposed in UI). But, Selecting 'Web App on Linux'  should work.

![image](https://user-images.githubusercontent.com/20121508/43790510-7600f39e-9a90-11e8-8409-90bda9c1a2cf.png)

**Comment by rand0me** [comment]
With this setting it takes almost infinity (25 mins and continues).
Could this happen, given that I'm trying to deploy a Function App?

**Comment by vincentdass** [comment]
@rand0me  , sorry for the delayed response.
Can you please leave the release for an hour and observe the behaviour. Debug logs would help in identifying the issue.

**Comment by jensholzhause** [comment]
We have the same issue on Azure DevOps Server. How can this be fixed?

**Comment by WillTheProgrammer** [comment]
I am experiencing the same issue. Any updates would be appreciated. Please see a full log of the output attached. 
[ADO_Log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/6928702/ADO_Log.txt)

**Comment by justinpenguin45** [comment]
Still seeit this behavior with app service zip deploy with a post deployment inline script. It's 2022 and this isn't fixed yet 😢

**Comment by max-mayorov** [comment]
I'm having the same issue...

**Comment by WolfyUK** [comment]
> I'm had the same issue... But apparently the problem was in `appType: 'webAppLinux'` , it was webApp instead of webAppLinux

This is still a valid fix in `@4` 🎊

**Comment by UtkuBulkan** [comment]
There is no label as appType, what do you exactly mean?

**Comment by Mohamed-Irshath** [comment]
I am experiencing this error still now. In v4 and v5
