### ISSUE TITLE
asp.net 5 app Publish-AzureWebDeployment embedded wwwroot folder

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/vsts-tasks#997]
ASP.NET 5 using `dnu publish` produces a folder structure like:
- site
    - approot
    - wwwroot

When deployed with the Azure Web App Deployment task, it ends up putting the approot and wwwroot under site/wwwroot in Azure web apps resulting in the actual wwwroot existing at site/wwwroot/wwwroot.

The only way I have managed to get this to work is modify the virtual application directories in the application settings, but it would be great if these deploy similar to VS publish deploys them appropriately without any change required.

**Comment by damienpontifex** [comment]
Could the kudu [Zip API](https://github.com/projectkudu/kudu/wiki/REST-API#zip) be used with a PUT request to https://{sitename}.scm.azurewebsites.net/api/zip/site which seems to enable the zip folder to be expanded in the site folder rather than the current implementation to deploy contents into wwwroot?

**Comment by damienpontifex** [comment]
I have now noticed the web publishing from visual studio uses the function `Publish-AspNet` in the powershell script used to deploy an aspnet5 application.

I may look at a custom PublishAspNet task and integrate if it works well

**Comment by kirkone** [comment]
Hi,
I had the same issue with publishing ASP.NET 5 Webs.
My solution was to publish a own task to the Marketplace.
You can have a look here [VSTS DNX Tasks Publish](https://github.com/kirkone/vsts-dnx-tasks/blob/master/VSTS.DNX.Tasks.PublishWebPackage/PublishWebPackage.ps1)
Maybe we can join forces and make this even better.
So long,
KirK

**Comment by damienpontifex** [comment]
This is solved now so closing

**Comment by Jargon64** [comment]
I am still experiencing this issue. Where exactly was this corrected? I'm currently using continuous deployment to deploy my project from BitBucket if that clarifies anything.
